# Generated by Django 2.0.1 on 2020-01-17 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conn_name', models.CharField(max_length=50)),
                ('computer_room', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=100)),
                ('port', models.IntegerField()),
                ('conn_user', models.CharField(max_length=50)),
                ('conn_pwd', models.CharField(max_length=50)),
                ('describe', models.CharField(max_length=100)),
            ],
        ),
    ]
