# Generated by Django 2.0.1 on 2020-01-17 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managedb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databaselist',
            name='describe',
        ),
    ]
