# Generated by Django 2.0.1 on 2020-01-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('managedb', '0002_remove_databaselist_describe'),
    ]

    operations = [
        migrations.CreateModel(
            name='SqlDictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dbname', models.CharField(max_length=100)),
                ('tablename', models.CharField(max_length=100)),
                ('field', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('null', models.CharField(max_length=100)),
                ('default', models.CharField(max_length=100)),
                ('extra', models.CharField(max_length=100)),
                ('tablecomment', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
